repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.64.dss
    hooks:
      - id: detect-secrets # pragma: whitelist secret
        args: [--baseline, .secrets.baseline, --use-all-plugins]
        exclude: '^uv(.lock)?$'
        stages:
          - pre-commit
          - pre-push

