[project]
name = "git-wrench"
version = "0.1.0"
description = "terminal-based multi-repo git workspace manager"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "tomli-w",
]

[dependency-groups]
dev = [
    "pre-commit",
    "pre-commit-hooks",
    "ruff",
    "pytest",
    "pytest-bdd",
    "pytest-cov",
    "pyright",
    "bandit",
    "pip-audit",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project.scripts]
git-wrench = "git_wrench.cli:main"

[tool.ruff]
line-length = 140
target-version = "py314"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "W",   # warnings
    "I",   # import sorting
    "B",   # bugbear
    "UP",  # pyupgrade
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["B011"]  # assert False is fine in tests

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
python_files = ["test_*.py"]
addopts = "-ra"

[tool.coverage.run]
source = ["bin"]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.bandit]
exclude_dirs = [
    ".venv",
    "build",
    "dist",
    "tests",
]
#skips = ["B101"] # More Info: https://bandit.readthedocs.io/en/1.9.4/plugins/b101_assert_used.html

[tool.bandit.assert_used]
skips = ["*/tests/*"]

[tool.pyright]
include = ["git_wrench", "bin"]
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
]
typeCheckingMode = "standard"

[tool.pip-audit]
ignore-vulns = []


[tool.hatch.build.targets.wheel]
packages = ["git_wrench"]
include   = ["main.py"]

